config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  devise_for :agents
  resources :locks
  resources :properties
  resources :agents
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "locks#new"

  namespace 'api' do
    namespace 'v1' do
     # get 'companies/id/get_properties',:defaults => { :format => 'json' }
      resources :companies,:defaults => { :format => 'json' }
      resources :agents,:defaults => { :format => 'json' }  
      resources :properties,:defaults => { :format => 'json' }      
    end
  end
end

app/models/lock.rb
class Lock < ApplicationRecord
  #validates :property_id, presence: true
  #validates :property_id, uniqueness: true
  validates :property_id, uniqueness: { allow_blank: true}
  belongs_to :company,optional: true
  belongs_to :property,optional: true

  def self.assign_locks(company_id)
    unassigned_locks = Lock.where(company_id: nil).limit(10)
    unassigned_locks.update_all(company_id: company_id)
  end
end

app/controllers/locks_controller.rb
class LocksController < ApplicationController
  before_action :set_lock, only: %i[ show edit update destroy ]

  # GET /locks or /locks.json
  def index
    @locks = Lock.all
  end

  # GET /locks/1 or /locks/1.json
  def show
  end

  # GET /locks/new
  def new
    @lock = Lock.new
  end

  # GET /locks/1/edit
  def edit
  end

  # POST /locks or /locks.json
  def create
    @lock = Lock.new(lock_params)

    respond_to do |format|
      if @lock.save
        format.html { redirect_to @lock, notice: "Lock was successfully created." }
        format.json { render :show, status: :created, location: @lock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locks/1 or /locks/1.json
  def update
    respond_to do |format|
      if @lock.update(lock_params)
        format.html { redirect_to @lock, notice: "Lock was successfully updated." }
        format.json { render :show, status: :ok, location: @lock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locks/1 or /locks/1.json
  def destroy
    @lock.destroy
    respond_to do |format|
      format.html { redirect_to locks_url, notice: "Lock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lock
      @lock = Lock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lock_params
      params.require(:lock).permit(:number,:company_id,:property_id)
    end
end

app/helpers/locks_helper.rb
module LocksHelper
end

app/views/locks/_form.html.erb
<%= form_with(model: lock) do |form| %>
  <% if lock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lock.errors.count, "error") %> prohibited this lock from being saved:</h2>

      <ul>
        <% lock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= 
    properties =Property.all
    selected_prop=[]
    properties.each do |prop|
     if @lock.company_id == prop.company_id
        selected_prop.push(prop)
     end
    end
    form.collection_select(:property_id,selected_prop, :id, :name)
    %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locks/edit.html.erb
<h1>Editing Lock</h1>

<%= render 'form', lock: @lock %>

<%= link_to 'Show', @lock %> |
<%= link_to 'Back', locks_path %>

app/views/locks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locks</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Company</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locks.each do |lock| %>
      <tr>
        <td><%= lock.number %></td>
        <td><%= lock.company_id %></td>
        <td><%= lock.property_id %></td>
        <td><%= link_to 'Show', lock %></td>
        <td><%= link_to 'Edit', edit_lock_path(lock) %></td>
        <td><%= link_to 'Destroy', lock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lock', new_lock_path %>

app/views/locks/new.html.erb
<h1>New Lock</h1>

<%= render 'form', lock: @lock %>

<%= link_to 'Back', locks_path %>

app/views/locks/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @lock.number %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lock.company_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @lock.property_id %>
</p>

<%= link_to 'Edit', edit_lock_path(@lock) %> |
<%= link_to 'Back', locks_path %>