config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  devise_for :agents
  resources :locks
  resources :properties
  resources :agents
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "locks#new"

  namespace 'api' do
    namespace 'v1' do
     # get 'companies/id/get_properties',:defaults => { :format => 'json' }
      resources :companies,:defaults => { :format => 'json' }
      resources :agents,:defaults => { :format => 'json' }  
      resources :properties,:defaults => { :format => 'json' }      
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Propertymanagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text float-right">
  <% if agent_signed_in? %>
  Logged in as <strong><%= current_agent.email %></strong>.
  <%= link_to 'Edit profile', edit_agent_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_agent_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_agent_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_agent_session_path, :class => 'navbar-link'  %>
  <% end %>
 </p>



  <%= yield %>
  </body>
</html>